version: '3.8'

volumes:
  postgres_data:


services:
  postgres:
    image: postgres:13.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local-pg
      POSTGRES_PASSWORD: local-pg
