# Generated by Django 3.0.5 on 2021-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210428_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Выберите жанр', related_name='titles', to='api.Genre', verbose_name='Жанр'),
        ),
    ]
